---
- name: update the apt cache on the repo server
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install the required packages on the repo server
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: create the apt keyring directory if it doesn't exist on the repo server
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: download docker's GPG key and dearmor it into the file
  ansible.builtin.shell: 
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: add the docker repository on the repo server
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes 

- name: install the required packages on the repo server
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_required_packages }}"
