---
- name: check if the repo already exists on the repo server
  ansible.builtin.uri:
    url: "http://{{ gitlab_fqdn | default(ansible_nodename) }}:3000/api/v1/repos/{{ gitlab_admin_user }}/{{ item.split('/') | last }}"
    method: GET
    user: "{{ gitlab_admin_user }}"
    password: "{{ gitlab_admin_passwd }}"
    force_basic_auth: yes
    return_content: yes
    status_code: 200
  register: _repo_check
  failed_when: _repo_check.status == 404
  ignore_errors: yes
  no_log: true

- debug:
    msg: "repo {{ item.split('/') | last }} will be created since it doesn't exist"
  when: _repo_check.status == 404

- debug:
    msg: "repo {{ item.split('/') | last }} exists!"
  when: _repo_check.status == 200

- name: create the repo in local gitlab if required on the repo server
  ansible.builtin.shell:
    cmd: git push --mirror http://{{ gitlab_admin_user }}:{{ gitlab_admin_passwd }}@{{ gitlab_fqdn | default(ansible_nodename) }}:3000/{{ gitlab_admin_user }}/{{ item.split('/') | last }}
  args:
    chdir: "{{ gitlab_tmp_dir }}/{{ item.split('/') | last }}"
    executable: /bin/bash
  when: _repo_check.status == 404
